'use client'

import { useEffect, useState } from 'react'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL ?? 'http://localhost', process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? 'placeholder')
type Company = { id: string; code: string; name: string }; type Policy = { filename: string; updatedAt: string }
export default function AdminPtoPolicyPage() { const [companies, setCompanies] = useState<Company[]>([]); const [company, setCompany] = useState(''); const [policy, setPolicy] = useState<Policy | null>(null); const [preview, setPreview] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  async function call(path: string, init?: RequestInit) { const { data } = await supabase.auth.getSession(); return fetch(path, { ...init, headers: { Authorization: `Bearer ${data.session?.access_token ?? ''}`, ...(init?.headers || {}) }, cache: 'no-store' }) }
  useEffect(() => { call('/api/admin/pto-policy').then(async r => { if (r.ok) { const x = await r.json(); setCompanies(x.companies); if (x.companies[0]) setCompany(x.companies[0].id) } }) }, [])
  useEffect(() => { if (!company) return; setPreview(''); call(`/api/admin/pto-policy?companyId=${company}`).then(async r => { if (r.ok) setPolicy((await r.json()).policy) }) }, [company])
  async function upload(file: File) { setBusy(true); setMessage(''); const body = new FormData(); body.append('file', file); const r = await call(`/api/admin/pto-policy?companyId=${company}`, { method: 'POST', body }); const x = await r.json(); setBusy(false); setMessage(r.ok ? 'Policy updated.' : x.error || 'Upload failed.'); if (r.ok) setPolicy(x.policy) }
  async function showPreview() { const r = await call(`/api/admin/pto-policy?companyId=${company}&preview=1`); if (r.ok) setPreview((await r.json()).policy?.markdown || '') }
  return <div className="max-w-3xl p-6 md:p-10"><h1 className="text-2xl font-bold">PTO Policy</h1><p className="mt-2 text-sm text-ink-muted">Upload the private Markdown document used by the Employee Portal.</p><section className="mt-8 rounded-3xl border border-line-soft bg-white p-7 shadow-sm"><label className="block text-sm font-semibold">Company<select value={company} onChange={e => setCompany(e.target.value)} className="mt-2 w-full rounded-xl border border-line px-4 py-3">{companies.map(c => <option key={c.id} value={c.id}>{c.name} ({c.code})</option>)}</select></label><div className="mt-7 rounded-2xl bg-pill p-5 text-sm">{policy ? <><p className="font-semibold">{policy.filename}</p><p className="mt-1 text-ink-muted">Last updated {new Date(policy.updatedAt).toLocaleString('en-CA')}</p></> : <p className="font-semibold">No PTO Policy uploaded</p>}</div><div className="mt-6 flex flex-wrap gap-3"><label className="cursor-pointer rounded-xl bg-ink px-5 py-3 text-sm font-semibold text-white">{busy ? 'Uploading…' : 'Upload .md'}<input type="file" accept=".md,text/markdown" className="hidden" disabled={busy || !company} onChange={e => e.target.files?.[0] && upload(e.target.files[0])} /></label><button onClick={showPreview} className="rounded-xl border border-line px-5 py-3 text-sm font-semibold">Preview current policy</button></div>{message && <p className="mt-4 text-sm text-ink-muted">{message}</p>}{preview && <pre className="mt-6 max-h-96 overflow-auto whitespace-pre-wrap rounded-2xl border border-line-soft bg-[#fafafa] p-5 text-sm">{preview}</pre>}</section></div> }
